services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - metadata

  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - db
    networks:
      - metadata

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NO_CACHE=1
    volumes:
      - .:/app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    env_file:
      - .env
    stdin_open: true  # Keep stdin open to allow user input
    tty: true         # Allocate a pseudo-TTY for interactive input
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    networks:
      - metadata

  spark-master:
    image: bitnami/spark:3.3.1
    container_name: spark-master
    user: root
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./downloads:/opt/spark/data
      - ./logs:/opt/spark/logs
    networks:
      - metadata

  spark-worker-1:
    image: bitnami/spark:3.3.1
    container_name: spark-worker-1
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./downloads:/opt/spark/data
      - ./logs:/opt/spark/logs
    depends_on:
      - spark-master
    networks:
      - metadata

  spark-worker-2:
    image: bitnami/spark:3.3.1
    container_name: spark-worker-2
    user: root
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./downloads:/opt/spark/data
      - ./logs:/opt/spark/logs
    depends_on:
      - spark-master
    networks:
      - metadata

networks:
  metadata:

volumes:
  db_data:
