spark:
  app_name: "Metadata"
  master: "spark://spark-master:7077"
  config:
    "spark.files": "app.pex"
    "spark.jars": "/opt/spark/jars/postgresql-42.7.3.jar"
  py_files:
    - "/opt/spark/jars/src.zip"
pyspark_python: "./app.pex"
